[[redirects]]
  from = "https://kvantik.com/rosp"
  to = "https://press.rosp.ru/publications/view/84252/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://kvan.tk/rosp"
  to = "https://press.rosp.ru/publications/view/84252/"
  status = 301
  force = true #COMMENT: ensure that we always redirect