
[[redirects]]
  # куда ведёт ссылка: список литературе к статье Клепцына «Слова на ленте» про число Фибоначчи
  # где размещена ссылка: Квантик 2020-06, с.6.
  from = "https://kvan.tk/fib-lit"
  to = "https://docs.google.com/document/d/e/2PACX-1vS4QT8cQodXdkR7sYlHdUIVR-8lj13A4PWcJrGBUMG1w3LHlzxFGUlkVDWtYG1ZWGpFL10W5lITdzxi/pub"
  status = 301
  force = true 

[[redirects]]
  # куда ведёт ссылка: электронные версии Квантика на сайте ЛитРес
  # где размещена ссылка: рекламная страница, все номера с 2020-06
  from = "https://kvan.tk/litres"
  to = "https://www.litres.ru/pages/rmd_search/?q=Квантик"
  status = 301
  force = true 

[[redirects]]
  # куда ведёт ссылка: Примеры магических квадратов из полимино
  # где размещена ссылка: Статья "Как Бусенька украшала торт" в сборнике сказок Кохася
  from = "https://kvan.tk/sloniki"
  to = "http://puzzlezapper.com/blog/2011/01/magic-squares-and-polyominoes/"
  status = 301
  force = true 


[[redirects]]
  # куда ведёт ссылка: видео с задачей Эйнштейна о чаинках
  # где размещена ссылка: статья "Эйнштейн, чашка чая и Картезианская медуза", с.8-10, Квантик 2020-05
  from = "https://kvan.tk/tealeaf"
  to = "https://www.youtube.com/watch?v=lQuKmZi7zvs"
  status = 301
  force = true 
[[redirects]]
  # куда ведёт ссылка: видео с картезианской медузой
  # где размещена ссылка: статья "Эйнштейн, чашка чая и Картезианская медуза", с.8-10, Квантик 2020-05
  from = "https://kvan.tk/jellyfish4"
  to = "https://upload.wikimedia.org/wikipedia/commons/a/a9/Cartesian_Jellyfish_4.webm"
  status = 301
  force = true 
[[redirects]]
  # куда ведёт ссылка: видео с картезианской медузой
  # где размещена ссылка: статья "Эйнштейн, чашка чая и Картезианская медуза", с.8-10, Квантик 2020-05
  from = "https://kvan.tk/jellyfish3"
  to = "https://upload.wikimedia.org/wikipedia/commons/2/2b/Cartesian_Jellyfish_3.webm"
  status = 301
  force = true 
[[redirects]]
  # куда ведёт ссылка: видео с картезианской медузой
  # где размещена ссылка: статья "Эйнштейн, чашка чая и Картезианская медуза", с.8-10, Квантик 2020-05
  from = "https://kvan.tk/jellyfish2"
  to = "https://upload.wikimedia.org/wikipedia/commons/4/4c/Cartesian_Jellyfish_2.webm"
  status = 301
  force = true 
[[redirects]]
  # куда ведёт ссылка: видео с картезианской медузой
  # где размещена ссылка: статья "Эйнштейн, чашка чая и Картезианская медуза", с.8-10, Квантик 2020-05
  from = "https://kvan.tk/jellyfish1"
  to = "https://upload.wikimedia.org/wikipedia/commons/b/b1/Cartesian_Jellyfish_1.webm"
  status = 301
  force = true 
[[redirects]]
  # куда ведёт ссылка: видео со всплытием картезианского водолаза
  # где размещена ссылка: статья "Эйнштейн, чашка чая и Картезианская медуза", с.8-10, Квантик 2020-05
  from = "https://kvan.tk/diver"
  to = "https://upload.wikimedia.org/wikipedia/commons/0/0a/Картезианский_водолаз.webm"
  status = 301
  force = true 



[[redirects]]
  # куда ведёт ссылка: развёртка тороидального многогранника из семиугольников
  # где размещена ссылка: статья "Многогранник из семиугольников?", с.8, Квантик 2020-04
  from = "https://kvan.tk/7dode-fold"
  to = "https://kvantik.com/extra/heptadodecahedron-fold.pdf"
  status = 301
  force = true 


[[redirects]]
  # куда ведёт ссылка: объёмное изображение тороидального многогранника из семиугольников
  # где размещена ссылка: статья "Многогранник из семиугольников?", с.8, Квантик 2020-04
  from = "https://kvan.tk/7dode"
  to = "http://dmccooey.com/polyhedra/HeptagonalDodecahedronC1.html"
  status = 301
  force = true 


[[redirects]]
  # куда ведёт ссылка: объёмное изображение тороидального многогранника из шестиугольников
  # где размещена ссылка: ответы к "Многогранник из семиугольников?", с.31, Квантик 2020-04
  from = "https://kvan.tk/6-toroid"
  to = "http://dmccooey.com/polyhedra/RegularHexagonalToroid12C1.html"
  status = 301
  force = true 




[[redirects]]
  # куда ведёт ссылка: на симулятор бросков кубика для парадокса последнего броска
  # где размещена ссылка: статья "Парадокс последней ручки", с.130, Квантик 2020-03
  from = "https://kvan.tk/lastpen"
  to = "https://kvantik.com/extra/lastpen/"
  status = 301
  force = true 

[[redirects]]
  # куда ведёт ссылка: на схему упрямоугольника на нашем сайте 
  # где размещена ссылка: статья "Упрямоугольник-8", с.130, Альманах 15
  from = "https://kvan.tk/upr-8"
  to = "https://kvantik.com/extra/upr8.pdf"
  status = 301
  force = true 

  [[redirects]]
  # куда ведёт ссылка: видео сифона на Викимедиа
  # где размещена ссылка: статья "Самозапускающийся сифон", Квантик 2020-01
  from = "https://kvan.tk/siphon"
  to = "https://upload.wikimedia.org/wikipedia/commons/5/53/Siphon.webm"
  status = 301
  force = true 
  
[[redirects]]
  # куда ведёт ссылка: видео самодельной чаши Тантала на Викимедиа
  # где размещена ссылка: статья "Самозапускающийся сифон", Квантик 2020-01
  from = "https://kvan.tk/tantalus"
  to = "https://upload.wikimedia.org/wikipedia/commons/2/2e/Tantalus_cup.webm"
  status = 301
  force = true 
  


[[redirects]]
  # куда ведёт ссылка: примеры иллюзии Манкера-Уайта на странице Дэвида Новика
  # где размещена ссылка: статья "Какого же цвета сердечки?", Квантик 2019-11
  from = "https://kvan.tk/novick"
  to = "http://engineering.utep.edu/novick/colors/"
  status = 301
  force = true 
  
[[redirects]]
  # куда ведёт ссылка: фотография NASA западного полушария Земли из космоса, сделанная Suomi NPP
  # где размещена ссылка: статья "Два фото Земли", Квантик 2019-10
  from = "https://kvan.tk/big-marble"
  to = "https://www.nasa.gov/multimedia/imagegallery/image_feature_2159.html"
  status = 301
  force = true 
  
[[redirects]]
  # куда ведёт ссылка: фотография NASA западного полушария Земли из космоса, сделанная MODIS
  # где размещена ссылка: статья "Два фото Земли", Квантик 2019-10
  from = "https://kvan.tk/small-marble"
  to = "https://commons.wikimedia.org/wiki/File:Earth_Western_Hemisphere_2002.png"
  status = 301
  force = true 
  

[[redirects]]
  # куда ведёт ссылка: электронные версии Квантика на сайте интернет-магазина МЦНМО
  # где размещена ссылка: рекламная страница, все номера с 2019-08
  from = "https://kvan.tk/e-shop"
  to = "https://biblio.mccme.ru/shop/order?field_authorstitleizdanie_value=%D0%9A%D0%B2%D0%B0%D0%BD%D1%82%D0%B8%D0%BA&field_book_year_value_op=%3D&field_book_year_value%5Bvalue%5D=&field_book_year_value%5Bmin%5D=&field_book_year_value%5Bmax%5D=&field_price_value_op=%3D&field_price_value%5Bvalue%5D=&field_price_value%5Bmin%5D=&field_price_value%5Bmax%5D=&field_book_kind_value_many_to_one=1"
  status = 301
  force = true 
  

[[redirects]]
  # куда ведёт ссылка: индекс Квантика на сайте Роспечати
  # где размещена ссылка: рекламная страница, Альманах 14, с.214, и все номера с 2019-08
  from = "https://kvan.tk/rosp"
  to = "https://press.rosp.ru/publications/view/84252/"
  status = 301
  force = true 
  

[[redirects]]
  # куда ведёт ссылка: копию сайта TEPCO с фотографиями тепловой электростанции Сендзю в Токио
  # где размещена ссылка: статья "призрачные трубы", Альманах 14 с.67
  from = "https://kvan.tk/tepco"
  to = "http://web.archive.org/web/20090521104632/http://www.adachi.ne.jp:80/users/a.trm/rokusyu.htm"
  status = 301
  force = true 
  

[[redirects]]
  # куда ведёт ссылка: ютюб-плейлист Квантика с видео притяжения и отталкивания тел на поверхности воды
  # где размещена ссылка: статья "ФОТОГРАФИИ СВОБОДНО ПЛАВАЮЩИХ ТЕЛ", Альманах 14 с.132
  from = "https://kvan.tk/float"
  to = "https://www.youtube.com/playlist?list=PLrjlKdQ24UtKcroglJPc0jRYK1mRiPqei"
  status = 301
  force = true 
  

[[redirects]]
  # куда ведёт ссылка: гугл-документ с инструкцией к математическому конкурсу
  # где размещена ссылка: Квантики, начиная с 2019-08, с.30
  from = "https://kvan.tk/matkonkurs"
  to = "https://docs.google.com/document/u/1/d/e/2PACX-1vS8oQI8oobwf7ZIzcshcBoSyhCtKzF-WXvbPoRNMrioeSvmPbwMfhMQhmzEllWx7izv8OskD3_o4Vo7/pub"
  status = 301
  force = true 
  
[[redirects]]
  # куда ведёт ссылка: 3D-модель гексаконтаэдра и триаконтаэдра
  # где размещена ссылка: Квантик 2019-09, с.23
  from = "https://kvan.tk/hexa-tria"
  to = "https://3dwarehouse.sketchup.com/model/5147b3d9-7fdc-4a99-9dcf-2cf02b502a19/Rhombic-Hexecontahedron-and-Rhombic-Triacontahedra-clusters-combined-to-form-Quasicrystal"
  status = 301
  force = true 


[[redirects]]
  from = "https://kvan.tk/*"
  to = "https://kvantik.com/shortener"
  status = 301
  force = true #COMMENT: ensure that we always redirect
