backend:
  name: github
  repo: aperep/hugo-kvantik
  branch: master

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads"

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "buy" # Used in routes, ie.: /admin/collections/:slug/edit
    extension: "yaml"
    label: "Магазины" # Used in the UI, ie.: "New Post"
    folder: "data/buy" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Список онлайн-магазинов данной категории"
        name: "store" 
        widget: "list"
        fields:
          - {label: "Название", name: "name", widget: "markdown"}
          - {label: "Продаёт", name: "sells", widget: "markdown"}
          - {label: "Доставка", name: "delivery", widget: "markdown"}
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    extension: "md"
    label: "Статьи" # Used in the UI, ie.: "New Post"
    folder: "content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
       - {label: "Название", name: "title", widget: "markdown"}

  - name: "pages"
    label: "Страницы"
    editor:
      preview: false
    files:
      - name: "subscription"
        label: "Подписка"
        description: "Подписка!"
        file: "content/subscription.md"
        fields: # The fields each document in this collection have
           - {label: "содержимое", name: "body", widget: "markdown"}

  - name: "carousel"
    label: "Карусель"
    extension: "yaml"
    folder: "data/carousel"
    create: true
    media_folder: "static/img/carousel"
    fields: # The fields each document in this collection have
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "string"}
      - {label: "Картинка", name: "image", widget: "image"}
      - {label: "Порядок", name: "weight", widget: "number"}
