backend:
  name: github
  repo: aperep/hugo-kvantik
  branch: oldstyle

media_folder: "static/img/partners" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/partners"

publish_mode: editorial_workflow

display_url: http://kvantik.org

collections: # A list of collections the CMS should be able to edit

  - name: "news"
    extension: "md"
    label: "Новости"
    label_singular: "новость"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
       - {label: "Название", name: "title", widget: "string"}
       - {label: "Содержание", name: "body", widget: "markdown"}

  - name: "partners"
    label: "Партнёры"
    label_singular: "Партнёр"
    media_folder: "static/img/partners"
    public_folder: "/img/partners"
    files:
      - label: "Список партнёров"
        name: "partners"
        file: "data/partners.yaml"
        fields:
          - label: "Партнёры"
            label_singular: "Партнёр"
            name: "partner"
            widget: "list"
            fields:
              - {label: "Ссылка", name: "url", widget: "string"}
              - {label: "Логотип", name: "logo", widget: "image"}
              - {label: "Название", name: "name", widget: "string", required: false}



  - name: "buy-online" # Used in routes, ie.: /admin/collections/:slug/edit
    extension: "yaml"
    label: "Онлайн-магазины"
    label_singular: "онлайн-магазин"
    folder: "data/buy/online" 
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - label: "Список онлайн-магазинов"
        label_singular: "онлайн-магазин"
        name: "store" 
        widget: "list"
        fields:
          - {label: "Название", name: "name", widget: "markdown"}
          - {label: "Продаёт", name: "sells", widget: "markdown"}
          - {label: "Доставка", name: "delivery", widget: "markdown"}
          - {label: "Введите 0, чтобы спрятать с сайта", name: "available", widget: "number"}
          - {label: "Архив: здесь хранится ненужное", name: "dump", widget: "markdown", required: false}

  - name: "buy-retail" # Used in routes, ie.: /admin/collections/:slug/edit
    extension: "yaml"
    label: "Розничные магазины" 
    label_singular: "регион" 
    folder: "data/buy/retail"
    create: true 
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - label: "Список розничных магазинов"
        name: "shops" 
        widget: "list"
        fields:
          - {label: "Название", name: "name", widget: "markdown"}
          - {label: "Контакты", name: "address", widget: "markdown"}
          - {label: "Введите 0, чтобы спрятать с сайта", name: "available", widget: "number"}
          - {label: "Архив: здесь хранится ненужное", name: "dump", widget: "markdown", required: false}
          - label: "Подразделения"
            name: "branches"
            widget: "list"
            required: false
            fields:
              - {label: "Название", name: "name", widget: "markdown"}
              - {label: "Контакты", name: "address", widget: "markdown"}
              - {label: "Введите 1, чтобы отобразить на сайте", name: "available", widget: "number"}
              - {label: "Архив: здесь хранится ненужное", name: "dump", widget: "markdown", required: false}

  - name: "pages"
    label: "Страницы"
    editor:
      preview: false
    files:
      - name: "subscription"
        label: "Подписка"
        description: "Подписка!"
        file: "content/subscription.md"
        fields: # The fields each document in this collection have
           - {label: "содержимое", name: "body", widget: "markdown"}

  - name: "carousel"
    label: "Карусель"
    extension: "yaml"
    folder: "data/carousel"
    create: true
    media_folder: "static/img/carousel"
    fields: # The fields each document in this collection have
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "string"}
      - {label: "Картинка", name: "image", widget: "image"}
      - {label: "Порядок", name: "weight", widget: "number"}
